spring:
#  mvc:
#    static-path-pattern: /res/**

  resources:
    static-locations: [classpath:/qtstatic/]
  mvc:
      contentnegotiation:
        favor-parameter: true  #Enable request parameter content negotiation mode

